ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0 # Filter output frequency (Hz)
    sensor_timeout: 0.5 # Increased timeout for sensor messages
    two_d_mode: true # Enforces 2D operation (ignores Z-axis)
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: true
    debug_out_file: /home/debug/odom_ekf_debug.txt
    publish_tf: true
    publish_acceleration: false
    reset_on_time_jump: true

    # Frames
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Odometry Settings
    odom0: /scout_1_1/odom
    odom0_config: [ true, true, false,     #[x_pos   , y_pos    , z_pos,
                    false, false, true,  # roll    , pitch    , yaw,
                    true, true, false,     # x_vel   , y_vel    , z_vel, 
                    false, false, true,   # roll_vel, pitch_vel, yaw_vel
                    false, false, false ] # x_accel , y_accel  , z_accel]
    odom0_queue_size: 2
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: true
    odom0_pose_rejection_threshold: 10.0 # Loosen rejection thresholds
    odom0_twist_rejection_threshold: 2.0

    # Override Odometry Covariance
    odom0_covariance: [0.2, 0.0, 0.0, 0.0, 0.0, 0.0,
                       0.0, 0.2, 0.0, 0.0, 0.0, 0.0,
                       0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
                       0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                       0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                       0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

    # IMU Settings
    imu0: /scout_1_1/imu
    imu0_config: [  false, false, false,  #[x_pos   , y_pos    , z_pos,
                    true,  true,  true,   # roll    , pitch    , yaw,
                    false, false, false,  # x_vel   , y_vel    , z_vel,
                    true,  true,  true,   # roll_vel, pitch_vel, yaw_vel,
                    true,  true,  true ]  # x_accel , y_accel  , z_accel]
    imu0_queue_size: 7
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true

    # Override IMU Covariance
    imu0_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                      0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                      0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                      0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                      0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

    imu0_pose_rejection_threshold: 1.5
    imu0_twist_rejection_threshold: 1.5
    imu0_linear_acceleration_rejection_threshold: 1.5

    # Control Inputs (disabled for now)
    use_control: false
    stamped_control: false
    control_timeout: 0.2
    control_config: [true, false, false, false, false, true] # vx, vy, vz, vroll, vpitch, vyaw.
    acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.4]
    deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 4.5]
    acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
    deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

    # Process Noise Covariance (Q)
    process_noise_covariance: [0.1,  0.0,  0.0,  0.0,  0.0,  0.0,
                               0.0,  0.1,  0.0,  0.0,  0.0,  0.0,
                               0.0,  0.0,  0.1,  0.0,  0.0,  0.0,
                               0.0,  0.0,  0.0,  0.1,  0.0,  0.0,
                               0.0,  0.0,  0.0,  0.0,  0.1,  0.0,
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.1]

    # Initial Estimate Covariance (P)
    initial_estimate_covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                                  0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                                  0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                                  0.0, 0.0, 0.0, 0.5, 0.0, 0.0,
                                  0.0, 0.0, 0.0, 0.0, 0.5, 0.0,
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.5]
