name: a_to_b
from_domain: 1
to_domain: 2
topics:
  /a/distributedMapping/globalDescriptors:
    type: multi_agent_mapping/msg/GlobalDescriptor
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /a/distributedMapping/loopInfo:
    type: multi_agent_mapping/msg/LoopInfo
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /a/distributedMapping/optimizationState:
    type: std_msgs/msg/Int8
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /a/distributedMapping/rotationEstimateState:
    type: std_msgs/msg/Int8
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /a/distributedMapping/poseEstimateState:
    type: std_msgs/msg/Int8
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /a/distributedMapping/neighborRotationEstimates:
    type: multi_agent_mapping/msg/NeighborEstimate
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /a/distributedMapping/neighborPoseEstimates:
    type: multi_agent_mapping/msg/NeighborEstimate
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50