name: b_to_a
from_domain: 2
to_domain: 1
topics:
  /b/distributedMapping/globalDescriptors:
    type: multi_agent_mapping/msg/GlobalDescriptor
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /b/distributedMapping/loopInfo:
    type: multi_agent_mapping/msg/LoopInfo
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /b/distributedMapping/optimizationState:
    type: std_msgs/msg/Int8
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /b/distributedMapping/rotationEstimateState:
    type: std_msgs/msg/Int8
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /b/distributedMapping/poseEstimateState:
    type: std_msgs/msg/Int8
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /b/distributedMapping/neighborRotationEstimates:
    type: multi_agent_mapping/msg/NeighborEstimate
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50
  /b/distributedMapping/neighborPoseEstimates:
    type: multi_agent_mapping/msg/NeighborEstimate
    qos:
      reliability: reliable
      durability: transient_local
      history: keep_last
      depth: 50